version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: banangbanang
    ports:
      - 8000:3000
    container_name: banangbanang
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    # volumes:
    # - ./redis/data:/data
    # - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    # labels:
    #   - 'name=redis'
    #   - 'mode=standalone'
    restart: always
